### ISSUE TITLE
Bug: Stack overflow issue with the game when playing for more than 2-3 mins (i.e. game gradually slows down and crashes)

### ISSUE THREAD

**Issue by SasanTazayoni** [stephendawsondev/j-day#50]
Some Javascript code seems to be generating something continuously but the item is not removed and therefore the stack seems to overflow

**Comment by Nazek-Altayeb** [comment]
The following is the investigation that has been done to indicates the issue:
The screenshot below shows that the loading issue is caused by : Largest Contentful Paint (LCP), 
that mean it could be better to have the images and sound loading done in the CSS file.


![Image](https://github.com/stephendawsondev/j-day/assets/123161903/cd563ea2-b507-43f9-b7da-047ff1d31fc1)

**Comment by stephendawsondev** [comment]
@Nazek-Altayeb Thanks for the update! Let us know if you need any help with it.

**Comment by Nazek-Altayeb** [comment]
@stephendawsondev 
i am trying to figure out how to move sounds and images files from js files  to style file,
do you think this could help ?

**Comment by stephendawsondev** [comment]
Sorry I missed this! Start a huddle with me and we can take a look.

**Comment by Nazek-Altayeb** [comment]
Hi @stephendawsondev 
Hello again ,
this is one of the resources i read could explain our freeze problem,
https://stackoverflow.com/questions/69166386/kaboom-makes-page-crash-and-browser-asks-to-block-javascript

**Comment by stephendawsondev** [comment]
This is resolved now.
